# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: LGPL-2.1


################################################################################
# Define object and action space 
################################################################################         
# Contains a list of common action verbs and their mapping to the RG specific action (as expected by the Simulation container)
# Use the first element of the set to create the regex match and the second to predict the RG compatible action
action_list = [("BURN", "Burn"), ("EXAMINE", "Examine"), ("SHOW", "Examine"), ("LOOK", "Look"), ("SCAN", "Scan"), ("TOGGLE", "Toggle"), ("PICKUP", "Pickup"), ("OPEN", "Open"), ("CLOSE", "Close"), ("PLACE", "Place"), ("MOVE", "Move"), ("GOTO", "Goto"), ("GO TO", "Goto"), ("GO FORWARD", "Move"), ("GO BACKWARD", "Move"), ("GO BACK", "Move"), ("PICK UP", "Pickup"), ("GRAB", "Pickup"), ("HOLD", "Pickup"), ("GET", "Pickup"), ("KEEP", "Place"), ("PUT", "Place"), ("INSERT", "Place"), ("SHUT", "Close"), ("PICK", "Pickup"), ("ROTATE", "Rotate"), ("TURN", "Rotate"), ("POUR", "Pour"), ("FILL", "Fill"), ("START", "Toggle"), ("THROW", "Throw"), ("CLEAN", "Clean"), ("CameraChange", "CameraChange"), ("SWITCH", "Toggle"), ("PUSH", "Toggle"), ("PRESS", "Toggle"), ("USE", "Use"), ("BREAK", "Break"), ("BORE", "Pour"), ("BORED", "Pour"), ("READ", "Examine")]

# Define a preposition list to be used for parsing
prepositions = [' that ', ' above ', ' across ', ' against ', ' along ', ' among ', ' around ', ' at ', ' before ', ' behind ', ' below ', ' beneath ', ' beside ', ' between ', ' by ', ' down ', ' from ', ' in ', ' into ', ' near ', ' off ', ' on ', ' to ', ' toward ', ' under ', ' upon ', ' with ']
    
# Defines the room names and their RG equivalent names    
room_names = [('break room', 'BreakRoom'), ('small office', 'SmallOffice'), ('manager office', 'SmallOffice'), ('managers office', 'SmallOffice'), ('main office', 'MainOffice'), ('quantum lab' ,'Lab2'), ('robotics','Lab1'), ('reception','Reception'), ('warehouse', 'Warehouse')]

valid_rooms = set([rn[1].strip() for rn in room_names])

readable_type_matching_dict = {
    "Fork_01" : "fork",
    "CoffeeMug_Yellow" : "coffeemug",
    "CoffeeMug_Yellow_ContainsCoffee" : "coffeemug", #note that this is substring of broken coffeemug
    'CoffeeMug_Boss': "coffeemug",
    'CoffeeMug_Boss_ContainsCoffee': "coffeemug",
    'CoffeeCup_Open_Empty_01': "coffeemug",
    'CoffeeCup_Open_Empty_02': "coffeemug",
    'CoffeeMug_Yellow_Broken' :  "brokencoffeemug",
    'CoffeeMug_Boss_Broken': "brokencoffeemug",
    "CoffeePotEmpty_01" : "coffeepot",
    "CoffeePot_01" : "coffeepot",
    'CoffeePot_WithCoffee_01': "coffeepot",
    "Jar_PeanutButter_01" : "jar",
    'Jar_PeanutButter_Eaten_01':  "jar",
    'Jar_Jam_Eaten_01': "jar",
    'CandyJar_01': 'jar',
    'Jar_Jam_01': 'jar',
    'CanSodaNew_01' : 'sodacan',
    'CanSoda_01': 'sodacan',
    'CanSodaNew_Open_01': 'sodacan',
    'CanSodaNew_Crushed_01': 'sodacan',
    "BreadSlice_01" : "bread",
    "CoffeeBeans_01" : "coffeebeans",
    "PaperCup_Crushed_01" : "papercup",
    "Knife_01" : "knife",
    "MilkCarton_01" : "milkcarton",
    "SandwichHalf_01" : "sandwich",
    'SandwichHalfEaten_01': "sandwich",
    "FoodPlate_01" : "plate",
    'FoodPlateDirty_01' : 'plate',
    'FoodPlateBroken_01': 'plate',
    "Bowl_01_Broken" : "brokenbowl", #Check whether to just map this to bowl 
    'Bowl_ContainsMilk_01' : 'bowl', #note that this is substring of brokenbowl and broken bowl needs to be matched first
    'Bowl_ContainsCereal_01' : 'bowl',
    'Bowl_ContainsMilkAndCereal' : 'bowl',
    'Bowl_ContainsCoffee' : 'bowl',
    'Bowl_01' : 'bowl',
    "CakeSlice_02" : "cake",
    'CakeCut_02': "cake",
    'SM_Prop_Table_02': 'table',
    'Table_Metal_01': 'table',
    'TableRound_02': 'table',
    'TableRoundSmall_02': 'table',
    'PaperCup_01': "papercup",
    'CandyBar_01' : 'candybar', 
    'CandyBar_Open_01': 'candybar',
    'CandyBar_Eaten_01': 'candybar',
    'Shelf_01' : 'shelf',
    'AP_Prop_Shelf_Wall_04' : "shelf",
    'AP_Prop_Shelf_06': "shelf",
    'Shelves_Tall_01': "shelf",
    'AP_Prop_Shelf_Wall_Laser': "shelf",
    'AP_Prop_Shelf_Wall_FreezeRay': "shelf",
    'Bookshelf_Wooden_01': "bookshelf", #Figure out how to distinguish this from sb phrase shelf
    'KitchenCabinet_02' : 'cabinet', #Notice that shelf and cabinet are different
    'KitchenCabinet_01' : 'cabinet',
    'KitchenCabinet_01_Trapped': 'cabinet',
    'KitchenCounterDrawer_03': 'drawer', #Keeping this separate from shelf/cabinet 
    'KitchenCounterDrawer_02': 'drawer', #Keeping this separate from shelf/cabinet 
    'ReceptionDesk' : 'desk', #Different from table
    'Desk_01' : 'desk',
    'ManagerDesk' : 'desk',
    'AP_Prop_Desk_Red' : 'desk',
    'AP_Prop_Desk_Green' : 'desk',
    'AP_Prop_Desk_Blue' : 'desk',
    'AP_Prop_Desk_Yellow' : 'desk',
    'Computer_Monitor_New' : "monitor", 
    'Computer_Monitor_01' : "monitor", 
    'V_Monitor_Laser' : 'lasermonitor',
    'V_Monitor_Gravity' : "monitor", 
    'V_Monitor_Embiggenator': 'monitor',
    'V_Monitor_FreezeRay': 'freezeraymonitor',
    'V_Monitor_Portal' : 'monitor',
    'Computer_Monitor_Broken': 'monitor',
    'Cake_02' : 'cake',
    'Pear_01' : 'pear',
    'Pear_01_Eaten': 'pear',
    'GravityPad' : 'gravitypad',
    'Hammer' : 'hammer',
    'Burger_04' : 'burger',
    'BreadLoaf' : 'bread',
    'ColorChanger_Button_Blue' : "bluecolorchangerbutton",
    'ColorChanger_Button_Green' : "greencolorchangerbutton",
    'ColorChanger_Button_Red' : "redcolorchangerbutton",
    'VendingMachine_01_E5_Button' : 'vendingmachinebutton', #See how to differentiate these if needed
    'VendingMachine_01_E7_Button' : 'vendingmachinebutton',
    'VendingMachine_01_B4_Button' : 'vendingmachinebutton',
    'VendingMachine_01_M8_Button' : 'vendingmachinebutton',
    'VendingMachine_01':  'vendingmachine',
    'BurgerEaten_04' : 'burger',
    'TrashCan_01' : 'trashcan',
    'Toast_01' : 'toast',
    'Toast_02' : 'toast',
    'Toast_03' : 'toast',
    'Toast_04' : 'toast',
    'Toast_04_Jam' : 'toast',
    'Toast_04_PBJ' : 'toast',
    'Toast_04_Jam_Eaten': 'toast',
    'Toast_04_PBJ_Eaten': 'toast',
    'Toast_04_Eaten': 'toast',
    'Cereal_Box_01': 'cerealbox',
    'YesterdayMachine_01' : 'yesterdaymachine',
    'Microwave_01' : 'microwave',
    'FridgeUpper_02': 'fridgeupper',
    'FridgeLower_02': 'fridgelower',
    'WallClock_01': 'clock',
    'Apple': 'apple',
    'AppleSlice_01' : 'apple',
    'AppleCut_01' : 'apple',
    'Apple_Eaten': 'apple',
    'DartBoard' : 'dartboard',
    'BreadLoaf_Sliced' : 'bread',
    'Dart' : 'dart',
    'Laser' : 'laser',
    'Laser_Tip' : 'lasertip',
    'Radio_01' : 'radio',
    'TeslaCoil' : 'teslacoil',
    'Door_01' : 'door',
    'Spoon_01' : 'spoon',
    'Banana_01': 'banana',
    'BananaBunch_01' : 'banana',
    'Banana_Peeled_01': "banana",
    'Banana_Eaten_01': "banana",
    'Trophy01' : 'trophy',
    'FireAlarm_01' : 'firealarm',
    'LightSwitch_01': 'switch',
    'Floppy_AntiVirus': 'floppy',
    'WaterCooler_01': 'watercooler',
    'Toaster_02' : 'toaster',
    'PortalGenerator': 'portalgenerator',
    'Record_01': 'record',
    'Record_01_Broken': 'record',
    'ForkLift': 'forklift',
    'RoboticArm_01': 'roboticarm',
    'CoffeeMaker_01': 'coffeemaker',
    'ColorChangerStation': 'colorchangerstation',
    'TAMPrototypeHead_01': 'tamhead',
    'EAC_Machine'  : 'eacmachine',
    'MissionItemHolder': 'missionitemholder',
    'KitchenStool_01': 'stool',
    'WaterPuddle_01': 'puddle',
    'FuseBox_02': 'fusebox',
    'FuseBox_01': 'fusebox',
    'FuseBox_01_Lever': 'lever',
    'PackingBox': 'box',
    'KitchenCounterBase_03': 'counter',
    'KitchenCounterBase_02': 'counter',
    'KitchenCounterTop_02': 'counter',
    'CounterBase_03' : 'counter',
    'KitchenCounter01': 'counter',
    'CoffeeUnMaker_01': 'unmaker',
    'FulllPaperTray_01': 'tray',
    'EmptyPaperTray': 'tray',
    'KitchenCounterSink_01': 'sink',
    'Handsaw': 'handsaw',
    'Screwdriver': 'screwdriver',
    'FreezeRay': 'freezeray',
    'Whiteboard_CoffeeUnmaker': 'whiteboard',
    'Whiteboard_YesterdayMachine': 'whiteboard',
    'WhiteBoard_01': 'whiteboard',
    'Broken_Cord_01': ' cord', #Space needed to differentiate from record
    'Printer_3D': 'printer',
    'Embiggenator': 'embiggenator',
    'Floppy_Virus': 'virus',
    'WarningSign_01' : 'warningsign',
    'Fork_Lift': 'forklift',
    'Carrot_01': 'carrot',
    'Carrot_Eaten_01': 'carrot',
    'PowerOutlet_01': 'poweroutlet',
    'Laser_CircuitBoard': 'circuitboard',
    'PinBoard_01': 'pinboard',
    'PinBoard_02': 'pinboard',
    'FireExtinguisher_01': 'extinguisher',
    'PieFruit_01': 'fruitpie',
    'PieFruitSlice_01': 'fruitpie',
    'PieFruitCut_01': 'fruitpie',
    'SafetyBarrier_02': 'safetybarrier',
    'DeskFan_Broken_01': 'fan',
    'DeskFan_New_01': 'fan',
    'CoffeeCup_Lid_01': 'lid',
    'CableFrayed_01': 'cable',
    'Printer_Cartridge': 'cartridge',
    'Donut_01': 'donut',
    'Donut_Eaten_01': 'donut',
    'StickyNote': 'stickynote',
    'Security_Button': 'securitybutton',
    'AutoChompers': 'chompers',
    'Laser_ControlPanel': 'controlpanel',
    #MS6 objects
    'Office_Chair': 'chair',
    'Manager_Chair': 'chair',
    'Keyboard': 'keyboard',
    'Printer_Cartridge_Lever': 'lever',
    'ActionFigure': 'actionfigure',
    'Cutting_Board': 'cutting board',
    'PBJ_Sandwich': 'sandwich',
    'TeslaCoil_Small': 'tesla coil',
    'Printer_Cartridge_Mug': 'mug',
    'Printer_Cartridge_Figure': 'actionfigurecartridge',
    'Floppy_AntiVirus_Broken': 'broken floppy',
    'Floppy_Virus_Broken': 'broken floppy',
    'Printer_Cartridge_Hammer': 'hammer',
    'Warehouse_Boxes': 'warehouse boxes',
    'Radio_01_Broken': 'broken radio',
    'LaserBase_toy': 'laser toy',
    #Some not used ones are mapped to a temporary string
    'SM_Bld_Wall_Window_Blinds_Open_04': 'notused',
    'SM_Prop_FlatPackCardboardBoxes_03': 'notused',
    'SK_Veh_Pickup_01_ToolBox': 'notused',
    'SM_Prop_Paper_Pile_01': 'notused',
    'AP_Prop_Lab_Tank_02': 'notused',
    'AP_Prop_Note_05': 'notused',
    'sign_short_caution_electrical': 'notused',
    'sign_tall_caution_carrot': 'notused',
    'sign_short_quantum_1': 'notused',
    'sign_tall_poster_tam_2': 'notused',
    'SM_Prop_PalletStack_02': 'notused',
    'SM_Prop_Book_Group_01': 'notused',
    'sign_diamond_carrot': 'notused',
    'AP_Prop_Minigolf_Club_01': 'notused',
    'SM_Prop_Paper_Pile_03': 'notused',
    'SM_Prop_Book_Group_07': 'notused',
    'SM_Tool_Drill_Chuck_01': 'notused',
    'SM_Prop_Book_Group_06': 'notused',
    'AP_Prop_Cabinets_01': 'notused',
    'SM_Prop_FolderTray_01': 'notused',
    'sign_short_caution_gravity_2': 'notused',
    'SM_Prop_Book_Group_05': 'notused',
    'SM_Prop_FlatPackCardboardBoxes_04': 'notused',
    'SM_Prop_FolderTray_04': 'notused',
    'SM_Bld_Wall_Metal_Slide_02': 'notused',
    'SM_Bld_Door_02': 'notused',
    'sign_short_poster_delwan_2': 'notused',
    'SM_Prop_Drink_Dispenser_01': 'notused',
    'SM_Prop_Paper_06': 'notused',
    'SM_Prop_Folder_PVC_01': 'notused',
    'AP_Prop_CorkBoard_02': 'notused',
    'SM_Prop_Warehouse_Light_04': 'notused',
    'sign_short_breakroom_2': 'notused',
    'SM_Prop_Buttons_05': 'notused',
    'SM_Prop_Folder_Holder_02': 'notused',
    'sign_short_warehouse_1': 'notused',
    'AP_Prop_Barrel_Water_01': 'notused',
    'AP_Prop_Folder_PVC_02': 'notused',
    'SM_Prop_Server_Node_01': 'notused',
    'SM_Prop_NetCable_03': 'notused',
    'SM_Prop_Book_Group_08': 'notused',
    'AP_Prop_Couch_06': 'notused',
    'sign_tall_caution_shrink': 'notused',
    'AP_Prop_Barrel_Open_01': 'notused',
    'SM_Prop_NotePad_01': 'notused',
    'SM_Prop_Book_Phone_Open_01': 'notused',
    'sign_tall_caution_freeze': 'notused',
    'sign_short_caution_restricted_1': 'notused',
    'SM_Item_Clipboard_01': 'notused',
    'SM_Prop_Cart_01': 'notused',
    'AP_Prop_Lab_Tank_01': 'notused',
    'sign_diamond_gravity': 'notused',
    'SM_Prop_Book_Group_02': 'notused',
    'SM_Prop_Book_Magazine_01': 'notused',
    'AP_Prop_Lab_MachinePanel_01': 'notused',
    'sign_short_caution_gravity_1': 'notused',
    'SM_Prop_Oxygen_Tank': 'notused',
    'AP_Prop_Fire_Extinguisher_01': 'notused',
    'SM_Prop_Folder_Holder_04': 'notused',
    'SM_Prop_FolderTray_03': 'notused',
    'AP_Prop_Plant_09': 'notused',
    'SM_Prop_Folder_PVC_02': 'notused',
    'SM_Prop_Lighting_Cable_Bulb_01': 'notused',
    'AP_Prop_Pen_01': 'notused',
    'SM_Prop_Wirespool_01': 'notused',
    'SM_Prop_Warehouse_Boxes_Stacked_04': 'notused',
    'sign_diamond_laser': 'notused',
    'sign_short_poster_delwan_1': 'notused',
    'SM_Prop_Book_Group_04': 'notused',
    'SM_Prop_Paper_04': 'notused',
    'SM_Prop_Server_Cabinet_01': 'notused',
    'sign_short_office_1': 'notused',
    'SM_Prop_AirVent_Wall_01': 'notused',
    'AP_Prop_Photocopier_01': 'notused',
    'SM_Prop_Certificate_01': 'notused',
    'SM_Prop_Wirespool_Small_01': 'notused',
    'AP_Prop_Safety_Barrier_02': 'notused',
    'sign_short_caution_shrink': 'notused',
    'sign_short_caution_quantum_2': 'notused',
    'SM_Prop_AirVent_01': 'notused',
    'AP_Prop_Pen_06': 'notused',
    'SM_Prop_PowerBoxes_01': 'notused',
    'sign_diamond_freeze': 'notused',
    'SM_Prop_Folder_Holder_01': 'notused',
    'AP_Prop_Bucket_02': 'notused',
    'AP_Prop_CardboardBox_Open_05': 'notused',
    'AP_Prop_Lab_Clamp_02_Arm_01': 'notused',
    'sign_tall_caution_electrical': 'notused',
    'sign_tall_poster_tam_1': 'notused',
    'SM_Prop_Folder_Holder_03': 'notused',
    'SM_Prop_Book_Group_03': 'notused',
    'SM_Prop_Folder_Manila_04': 'notused',
    'AP_Prop_Plant_01': 'notused',
    'Laser_Tip_Broken': 'notused',
    'AP_Prop_Lab_MachinePanel_02': 'notused',
    'sign_diamond_shrink': 'notused',
    'SM_Prop_Warehouse_Boxes_Stacked_03': 'notused',
    'sign_square_breakroom': 'notused',
    'SM_Prop_Powercable_02': 'notused',
    'AP_Prop_CardboardBox_Stack_02': 'notused',
    'SM_Tool_Buffer_01_Battery': 'notused',
    'SM_Prop_Calender_01': 'notused',
    'AP_Item_Tape_01': 'notused',
    'SM_Prop_Oxygen_Tank_Large': 'notused',
    'SM_Prop_Powercable_01': 'notused',
    'AP_Prop_Couch_02': 'notused',
    'SM_Prop_Papers_01': 'notused',
    'SM_Prop_Crate_Stack_01': 'notused',
    'SM_Prop_Plastic_Pipe_Spool_01': 'notused',
    'AP_Bld_Wall_Glass_Large_Door_01': 'notused',
    'sign_short_quantum_2': 'notused',
    'sign_diamond_fire': 'notused',
    'sign_short_robotics_1': 'notused',
    'SM_Prop_Powercable_03': 'notused',
    'SM_Prop_Folder_Manila_01': 'notused',
    'AP_Prop_Cellotape_01': 'notused',
    'sign_short_poster_delwan_4': 'notused',
    'SM_Tool_Handsaw_01': 'notused',
    'SM_Prop_Buttons_02': 'notused',
    'AP_Prop_Bin_Rubbish_01': 'notused',
    'SM_Prop_Scales_01': 'notused',
    'SM_Sign_Exit_02': 'notused',
    'sign_short_robotics_2': 'notused',
    'SM_Prop_Paper_05': 'notused',
    'SM_Prop_Warehouse_Platform_Trolley_01': 'notused',
    'sign_tall_caution_robotics': 'notused',
    'sign_short_poster_delwan_3': 'notused',
    'AP_Prop_Pen_03': 'notused',
    'AP_Item_Tool_Board': 'notused',
    'AP_Prop_PaperTray_01_Full_01': 'notused',
    'AP_Prop_Generator_Large_02': 'notused',
    'AP_Bld_Ceiling_Aircon_01': 'notused',
    'sign_tall_caution_laser': 'notused',
    'sign_short_breakroom_1': 'notused',
    'SM_Prop_Folder_Manila_02': 'notused',
    'AP_Prop_Print_Tube_01': 'notused',
    'Lab_Terminal': 'notused',
    'Deembiggenator_Crates': 'notused'
} 


synonym_mapping = {
    "unmaker" : ['unmaker', 'coffee time machine'],
    "coffeemug" : ["coffeemug", "coffee mug", "coffee cup", "cup ", " cup", "mug ", " mug", "glass"],
    "coffeepot" : ["coffeepot", "coffee pot", " pot ", "kettle"],
    "jar" : ["jar", "container"],
    "coffeebeans" : ["coffeebeans", "coffee beans", "beans", "coffee bag"],
    "papercup" : ["papercup", "paper cup"],
    "milkcarton" : ["carton", "milk"], #"milkcarton", "milk carton",
    "brokenbowl" : ["brokenbowl", "broken bowl"], # Broken bowl gets mapped to bowl but not vice verse
    "bowl" : ["bowl", "ball", "boat", "bull"], #Adding ASR misrecognitions
    "brokencoffeemug" : ["brokencoffeemug", "broken mug", "broken cup", "broken coffee mug", "broken coffee cup", "coffeemug", "coffee mug", "coffee cup"],  #broken cup gets mapped to all the cup synonyms but not vice versa
    'table' : ["table"], #Different from desk
    'desk'  : ["desk"],  #Different from table
    'candybar': ['candybar', 'candy bar'],
    'shelf' : ['shelf', 'rack'],
    'cabinet' : ['cabinet', 'closet'],
    "monitor" : ["monitor", "desktop", "display", "screen", "computer"], #See whether to differentiate between computer screen and other screens
    'vendingmachinebutton' : ['vendingmachinebutton', 'vending machine button'],
    'gravitypad' : ['gravitypad', 'gravity pad'],
    "bluecolorchangerbutton" : ["bluecolorchangerbutton", "blue color changer button", "blue colorchanger button", "blue button"],
    "greencolorchangerbutton" : ["greencolorchangerbutton", "green color changer button", "green colorchanger button", "green button"],
    "redcolorchangerbutton" : ["redcolorchangerbutton", "red color changer button", "red colorchanger button", "red button"],
    'trashcan' : ['trash', 'litterbox', 'litter box'], #trash includes all of 'trashcan', 'trash can', 'trash bin' etc
    'cerealbox' : ['cereal', 'serial'], #Includes 'cerealbox' and 'cereal'
    'yesterdaymachine' : ['yesterdaymachine', 'yesterday machine', 'time machine'],#, 'timemachine', 'time machine'], #, 'microwave'], #Decide whether to be Adding microwave since this looks like it
    'microwave' : ['microwave', 'micro wave'],
    'fridgeupper' : ['freezer'], 
    'fridgelower' : ['fridge', 'refrigerator'], 
    'dartboard'  : ['dartboard', 'dart board', 'bulls eye', 'bull eye', 'throwing'],
    'dart' : ['dart', 'dark', 'dot'], #Temorarily adding to allow mispronounced words to be caught
    'toast' : ['toast', 'bread'], #also in breadloaf
    'lasertip' : ['lasertip', 'laser tip'],
    'teslacoil': ['teslacoil', 'tesla coil'],
    'firealarm': ['firealarm', 'fire alarm'],
    'watercooler': ['watercooler' , 'water cooler'],
    'portalgenerator': ['portal', 'portal generator'],
    'record': ['record', 'disk', 'vinyl'],
    'forklift': ['forklift', 'fork lift'],
    'roboticarm': ['roboticarm', 'robotic arm'],
    'coffeemaker': ['coffeemaker', 'coffee maker', 'coffee machine'],
    'colorchangerstation': ['color swapper', 'color changer', 'colorchanger'],
    'eacmachine': ['eacmachine', 'eac machine'],
    'puddle': ['puddle', 'spill'],
    'fusebox': ['fusebox', 'fuse box', 'fuse'],
    'lever': ['lever', 'handle'],
    'counter': ['counter', 'countertop', 'slab', 'counter top', 'counter base'],
    'sodacan': ['sodacan', 'soda can', 'coke', 'pop', 'soda'],
    'screwdriver': ['screwdriver', 'screw driver'],
    "bookshelf": ["bookshelf", "book shelf"],
    'freezeray': ['freezeray', 'freeze ray'],
    'whiteboard': ['whiteboard', 'white board'],
    'vendingmachine': ['vendingmachine', 'vending machine'],
    'warningsign': ['warning sign', 'hazard sign'],
    'forklift': ['forklift', 'fork lift'],
    'poweroutlet': ['poweroutlet', 'outlet', 'plug', 'socket'],
    'circuitboard': ['circuitboard', 'circuit board'],
    'pinboard': ['pinboard', 'pin board'],
    'fruitpie': ['fruitpie', 'fruit pie', 'pie'],
    'safetybarrier': ['safetybarrier', 'safety barrier'],
    'fan': [' fan', 'fan '], #extra space so as not to confuse with larger words with fan as substring
    'lid': [' lid', 'lid '], #extra space so as not to confuse with larger words with fan as substring
    'stickynote': ['sticky', 'note', 'hint'],
    'securitybutton': ['security button'],
    'controlpanel': ['controlpanel', 'control panel'],
    #'fridge': ['fridge', 'refrigerator'],
    'keyboard': ['keyboard', 'key board'],
    'actionfigure': ['actionfigure', 'action figure'],
    'floppy': ['floppy', 'disk'],
    'switch': ['switch', 'light'],
    'actionfigurecartridge': ['action figure cartridge'],
    'lasermonitor': ['laser monitor'],
    'freezeraymonitor': ['freeze ray monitor']
}         

# Needed if vision model is used    
object_to_vision_class = {
    'fridgeupper':'Freezer',
    'cutting board': 'Cutting Board',
    'door': 'Door',
    'missionitemholder': 'Unassigned',
    'tamhead': 'Computer',
    'handsaw': 'Handsaw',
    'broken radio': "Radio",
    'dartboard': "Target",
    'extinguisher': "Fire Extinguisher",
    'controlpanel': "Control Panel",
    'sodacan': "Can",
    'cartridge': "Printer Cartridge",
    'actionfigurecartridge': "Printer Cartridge",
    'cable': "Cable",
    'carrot': "Carrot",
    'fork': "Fork",
    'warehouse boxes': "Boxes",
    'colorchangerstation': "Color Changer",
    'securitybutton': "Button",
    'printer hammer': "Hammer",
    'clock': "Clock",
    'coffeemug': "Mug",
    'laser toy': "Laser",
    'bread': "Bread",
    'redcolorchangerbutton': "Button",
    'pinboard': "Board",
    'keyboard': "Keyboard",
    'coffeebeans': "Coffee Beans",
    'banana':"Banana",
    'switch': "Light Switch",
    'lasertip': "Laser Tip",
    'milkcarton': "Milk",
    'printer mug': "Mug",
    'roboticarm': "Robot Arm",
    'apple': "Apple",
    'watercooler': "Water Cooler",
    'toast': "Bread",
    'toaster': "Toaster",
    'gravitypad': "Gravity Pad",
    'jar': "Jar",
    'chair':"Chair",
    'warningsign': "Sign",
    'greencolorchangerbutton': "Button",
    'circuitboard': "Circuit Board",
    'eacmachine': 'Everythings A Carrot Machine',
    'stickynote': "Sticky Note",
    'coffeemaker': "Coffee Maker",
    'teslacoil':"Tesla Coil",
    'cake': "Cake",
    'candybar': "Candy Bar",
    'record': "Record",
    'bowl': "Bowl",
    'cabinet': "Cabinet",
    'spoon': "Spoon",
    'table': "Table",
    'lid': "Lid",
    'drawer': "Drawer",
    'vendingmachine': "Vending Machine",
    'forklift': "Forklift",
    'fruitpie': "Pie",
    'firealarm': "Fire Alarm",
    'yesterdaymachine': "Time Machine",
    'burger': "Sandwich",
    'bookshelf': "Shelf",
    'fan': "Fan",
    'poweroutlet': "Outlet",
    'printer figure': "Action Figure",
    'hammer': "Hammer",
    'fridgelower': "Fridge",
    'desk': "Table",
    'papercup': "Cup",
    'shelf': "Shelf",
    'puddle': "Puddle",
    'trashcan': "Trash Can",
    'cerealbox': "Cereal Box",
    'floppy': "Floppy Disk",
    'radio': "Radio",
    'plate': "Plate",
    'actionfigure': "Action Figure",
    ' cord': "Cable",
    'cord': "Cable",
    'sink': "Sink",
    'knife': "Knife",
    'brokencoffeemug': "Mug",
    'printer': "Printer",
    'chompers': "Unassigned",
    'lever': "Lever" ,
    'fusebox': "Fuse Box",
    'broken floppy': "Floppy Disk",
    'trophy': "Trophy",
    'counter': "Counter Top",
    'embiggenator': "Embiggenator",
    'bluecolorchangerbutton': "Button",
    'tesla coil': "Tesla Coil",
    'coffeepot': "Coffee Pot",
    'whiteboard': "Board",
    'sandwich': "Sandwich",
    'brokenbowl': "Bowl",
    'unmaker': "Coffee Unmaker",
    'vendingmachinebutton': "Button",
    'stool': "Stool",
    'box': "Boxes",
    'donut': "Donut",
    'tray': "Tray",
    'safetybarrier': "Sign",
    'dart': "Dart",
    'freezeray': "Freeze Ray",
    'portalgenerator': "PortalGenerator",
    'monitor': "Computer",
    'lasermonitor': "Computer",
    'freezeraymonitor': "Computer",
    'laser': "Laser",
    'virus': "Floppy Disk",
    'notused': "Unassigned",
    'screwdriver': "Screw Driver",
    'microwave': "Microwave",
    'pear': "Pear"    
}
